from .dpo import DirectPreferenceOptimizationLoss
from .generation import (
    BeamHypothesis,
    beam_search,
    decode_indices_to_markup,
    greedy_search,
)
from .loss import (
    SpatialAwareHybridLoss,
    TeacherForcingCrossEntropy,
    apply_word_dropout,
    build_adamw_optimizer,
    build_cosine_warmup_scheduler,
    build_teacher_forcing_pair,
    build_token_loss_weights,
    warmup_cosine_ratio,
)
from .metrics import (
    DEFAULT_COORDINATE_SCALE,
    EvaluationMetrics,
    GeometricPrimitive,
    batch_geometric_edit_distance,
    batch_geometric_graph_edit_distance,
    batch_visual_similarity,
    corpus_bleu,
    evaluate_batch,
    geometric_edit_distance,
    geometric_graph_edit_distance,
    structural_similarity,
)
from .model import (
    ConvResidualBlock,
    VisionAutoregressiveModel,
    VisionEncoder,
    build_2d_sinusoidal_positional_encoding,
    resolve_device,
)
from .reporting import (
    compute_mean_and_std,
    format_mean_std,
    generate_ablation_latex_table,
    generate_multitier_latex_table,
    save_latex_tables,
)
from .trainer import TrainingMetrics, fit, iter_batch_bounds, train_one_epoch

__all__ = [
    "BeamHypothesis",
    "ConvResidualBlock",
    "DEFAULT_COORDINATE_SCALE",
    "DirectPreferenceOptimizationLoss",
    "EvaluationMetrics",
    "GeometricPrimitive",
    "SpatialAwareHybridLoss",
    "TeacherForcingCrossEntropy",
    "VisionAutoregressiveModel",
    "VisionEncoder",
    "apply_word_dropout",
    "build_2d_sinusoidal_positional_encoding",
    "build_token_loss_weights",
    "resolve_device",
    "TrainingMetrics",
    "batch_geometric_edit_distance",
    "batch_geometric_graph_edit_distance",
    "batch_visual_similarity",
    "beam_search",
    "build_adamw_optimizer",
    "compute_mean_and_std",
    "decode_indices_to_markup",
    "build_cosine_warmup_scheduler",
    "build_teacher_forcing_pair",
    "corpus_bleu",
    "evaluate_batch",
    "fit",
    "format_mean_std",
    "generate_ablation_latex_table",
    "generate_multitier_latex_table",
    "geometric_edit_distance",
    "geometric_graph_edit_distance",
    "greedy_search",
    "iter_batch_bounds",
    "restore_checkpoint",
    "save_latex_tables",
    "snapshot_checkpoint",
    "structural_similarity",
    "train_one_epoch",
    "warmup_cosine_ratio",
]
