from dataclasses import dataclass
import torch
from core.exceptions import TensorTopologyError, SyntaxTopologicalError

@dataclass(frozen=True)
class ImageTensor:
    """
    Immutable representation of an image batch propagating through the network.
    Guarantees structural validity upon instantiation in strictly O(1) time.
    """
    raw_tensor: torch.Tensor

    def __post_init__(self) -> None:
        if not isinstance(self.raw_tensor, torch.Tensor):
            raise TensorTopologyError("Input must be a torch.Tensor instance.")
        
        # Shape verification: (B, C, H, W)
        if self.raw_tensor.ndim != 4:
            raise TensorTopologyError(
                f"Invalid tensor topology. Expected 4 dimensions (B, C, H, W), got {self.raw_tensor.ndim}."
            )

@dataclass(frozen=True)
class TikzTokens:
    """
    Immutable structural markup generated by the VLM.
    Guarantees syntactical existence (not compilation correctness, but bounds).
    """
    markup: str

    def __post_init__(self) -> None:
        if not isinstance(self.markup, str):
            raise SyntaxTopologicalError("Markup must be a string sequence.")
        
        stripped_markup = self.markup.strip()
        if not stripped_markup:
            raise SyntaxTopologicalError("Generative markup cannot be an empty sequence.")
        
        if r"\begin{tikzpicture}" not in stripped_markup:
            raise SyntaxTopologicalError("Markup sequence lacks topological bounding environment (tikzpicture).")

@dataclass(frozen=True)
class CompilationResult:
    """
    Immutable product of the external TeX compilation sub-process.
    """
    pdf_data: bytes
    is_successful: bool

@dataclass(frozen=True)
class RawLatexDocument:
    """
    Immutable representation of an unparsed LaTeX source text fetched from external sources.
    Ensures O(1) string instantiation invariants for safe ingestion.
    """
    raw_text: str

    def __post_init__(self) -> None:
        if not isinstance(self.raw_text, str):
            raise SyntaxTopologicalError("Raw document payload must be a pure string.")
