from abc import ABC, abstractmethod
from core.models import ImageTensor, TikzTokens, CompilationResult

class ModelInferencePort(ABC):
    """
    Outbound port defining the mathematical contract for Neural Network inference.
    
    This interface ensures that the central Use Case orchestrator is isolated from
    the specific VLM topology (e.g., Vision Transformers, Auto-regressive Decoders).
    """

    @abstractmethod
    def infer_markup(self, image: ImageTensor) -> TikzTokens:
        """
        Executes the generative mapping from spatial domain to geometric syntax.

        Args:
            image (ImageTensor): The statically validated, immutable input tensor.

        Returns:
            TikzTokens: The strictly bounded and immutable sequence of LaTeX markup
                        generated by the underlying neural architecture.

        Raises:
            DomainError: If logical constraints are violated during inference.
        """
        pass


class TexCompilerPort(ABC):
    """
    Outbound port defining the infrastructural contract for TeX Live compilation.
    
    This interface ensures that the pure mathematical domain is isolated from
    subprocess execution, OS-level I/O operations, and binary payload generation.
    """

    @abstractmethod
    def compile_tikz(self, tokens: TikzTokens) -> CompilationResult:
        """
        Compiles the bounded syntactic sequence into a binary artifact (e.g., PDF).

        Args:
            tokens (TikzTokens): The structurally validated LaTeX sequence.

        Returns:
            CompilationResult: The product of compilation encapsulating success status
                               and arbitrary binary payload data.

        Raises:
            DomainError: If the syntactic sequence structurally fails to map to
                         geometric primitives during compilation.
        """
        pass
