from abc import ABC, abstractmethod

from core.models import CompilationResult, ImageTensor, RawLatexDocument, TikzTokens


class ModelInferencePort(ABC):
    """
    Outbound port defining the mathematical contract for Neural Network inference.

    This interface ensures that the central Use Case orchestrator is isolated from
    the specific VLM topology (e.g., Vision Transformers, Auto-regressive Decoders).
    """

    @abstractmethod
    def infer_markup(self, image: ImageTensor) -> TikzTokens:
        """
        Executes the generative mapping from spatial domain to geometric syntax.

        Args:
            image (ImageTensor): The statically validated, immutable input tensor.

        Returns:
            TikzTokens: The strictly bounded and immutable sequence of LaTeX markup
                        generated by the underlying neural architecture.

        Raises:
            DomainError: If logical constraints are violated during inference.
        """
        pass

class LatexSourcePort(ABC):
    """
    Outbound port defining the infrastructural contract for fetching LaTeX sources.

    This interface ensures that data ingestion pipelines can collect string primitives
    from remote sources and reliably parse them into the pure structural domain representation
    without leaking I/O constructs into the mathematical core.
    """

    @abstractmethod
    async def fetch_sources(self, source_identifiers: list[str]) -> list[RawLatexDocument]:
        """
        Asynchronously retrieves raw LaTeX data and maps it to domain entities.

        Args:
            source_identifiers (list[str]): The URIs or path identifiers to retrieve.

        Returns:
            list[RawLatexDocument]: The sequence of retrieved unparsed sources.

        Raises:
            DomainError: If ingestion strictly fails or sources violate bounds.
        """
        pass

class TexCompilerPort(ABC):
    """
    Outbound port defining the infrastructural contract for TeX Live compilation.

    This interface ensures that the pure mathematical domain is isolated from
    subprocess execution, OS-level I/O operations, and binary payload generation.
    """

    @abstractmethod
    async def compile_tikz(self, tokens: TikzTokens) -> CompilationResult: #async: if it´s not async the compiler it will block the main thread
        """
        Compiles the bounded syntactic sequence into a binary artifact (e.g., PDF).

        Args:
            tokens (TikzTokens): The structurally validated LaTeX sequence.

        Returns:
            CompilationResult: The product of compilation encapsulating success status
                               and arbitrary binary payload data.

        Raises:
            DomainError: If the syntactic sequence structurally fails to map to
                         geometric primitives during compilation.
        """
        pass


class ImageLoaderPort(ABC):
    """
    Outbound port defining the infrastructural contract for generic image tensor ingestion.

    This interface encapsulates file system or remote I/O, allowing the mathematical
    core or Use Cases to fetch and validate spatial data without coupling to specific
    decoding libraries.
    """

    @abstractmethod
    def load_image(self, source_path: str) -> ImageTensor:
        """
        Loads an image from the given source identifier and transforms it into the domain tensor.

        Args:
            source_path (str): The absolute path or URI to the image resource.

        Returns:
            ImageTensor: The structurally validated tensor with shape (B, C, H, W).

        Raises:
            DomainError: If the source is inaccessible or cannot be strictly parsed into a tensor.
        """
        pass
